version: 0.2
phases:
  install:
    commands:
    - make init
  build:
    commands:
    - make compile-app
    - make test
    - make deploy APP_STACK_NAME=$(CODEBUILD_BUILD_ID)
    - make teardown APP_STACK_NAME=$(CODEBUILD_BUILD_ID)