version: 0.2

phases:
  install:
    commands:
    - make init
  pre_build:
    commands:
    - apt-get install uuid-runtime
    - uuidgen -r
    - uuid=$(uuidgen -r)
    - x=FeatureToggles-$uuid
  build:
    commands:
    - make compile-app
    - make test
    - make deploy APP_STACK_NAME=$x
    - make teardown APP_STACK_NAME=$x