AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  LogLevel:
    Type: String
    Description: Log level for lambda functions.
    Default: INFO
    AllowedValues: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
  TogglesPrefix:
    Type: String
    Description: Prefix String for SSM Parameters
    Default: FeatureToggles
    

Resources:
  LoadFeatureToggles:
    Type: 'AWS::Serverless::Function'
    Properties:
      Tracing: Active
      CodeUri: ./src
      MemorySize: 512
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          PREFIX: !Ref TogglesPrefix
      Handler: handlers.load_feature_toggles
      Role: !GetAtt LoadFeatureTogglesRole.Arn
      Timeout: 60
      Runtime: python2.7

  LoadFeatureTogglesRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: LoadFeatureTogglesRolePolicy0
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - 'ssm:GetParameter*'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${TogglesPrefix}*'

      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  UpdateFeatureToggles:
    Type: 'AWS::Serverless::Function'
    Properties:
      Tracing: Active
      CodeUri: ./src
      MemorySize: 512
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel          
          PREFIX: !Ref TogglesPrefix
      Handler: handlers.update_feature_toggles
      Role: !GetAtt UpdateFeatureTogglesRole.Arn
      Timeout: 60
      Runtime: python2.7
      
  UpdateFeatureTogglesRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: UpdateFeatureTogglesRolePolicy0
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - 'ssm:GetParameter*'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${TogglesPrefix}*'

      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com


Outputs:
  LoadFeatureTogglesFunctionName:
    Value: !Ref LoadFeatureToggles
  LoadFeatureTogglesFunctionArn:
    Value: !GetAtt LoadFeatureToggles.Arn
  UpdateFeatureTogglesFunctionName:
    Value: !Ref UpdateFeatureToggles
  UpdateFeatureTogglesFunctionArn:
    Value: !GetAtt UpdateFeatureToggles.Arn